services:
  - type: web
    name: pulsepoll-zara-backend
    runtime: go
    rootDir: backend
    plan: free
    buildCommand: go build -o server ./cmd/server/main.go
    startCommand: ./server
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
      - key: MONGODB_URI
        value: "mongodb+srv://pulseadmin:Pollpass%40123@pulsepoll.wzxqp9i.mongodb.net/pulsepoll_db?retryWrites=true&w=majority&appName=pulsepoll"
      - key: MONGODB_NAME
        value: "pulsepoll_db"
      - key: REDIS_ADDR
        value: "localhost:6379"
      - key: REDIS_PASSWORD
        value: ""
      - key: REDIS_DB
        value: "0"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY_HOURS
        value: "72"
      - key: CLIENT_ORIGIN
        value: "https://pulsepoll-zara-frontend.onrender.com"
      - key: FALLBACK_MODE
        value: "true"

  - type: web
    name: pulsepoll-zara-frontend
    runtime: static
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://pulsepoll-zara-backend.onrender.com/api"
      - key: VITE_WS_HOST
        value: "pulsepoll-zara-backend.onrender.com"
